In [2]:
import pickle
import numpy as np

In [3]:
with open('../output/log-doc-tf-topk-10.pkl', 'rb') as f:
    doc_tf = pickle.load(f)


In [9]:
with open('../output/corpus-tf-log-tensor-dict.pkl', 'rb') as f:
    log_idf=pickle.load(f)

In [17]:
log_idf.type(torch.float32).cpu().numpy()

array([1.3862944, 0.       , 0.       , ..., 0.       , 0.       ,
       0.       ], dtype=float32)

In [21]:
emb.astype(np.float32)

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [19]:
import numpy as np
emb=np.zeros_like(log_idf)

In [16]:
ind=list(doc_tf[571018].keys())
values=list(doc_tf[571018].keys())
emb*=0
emb[ind]=values


TypeError: can't assign a list to a torch.FloatTensor

In [4]:
doc_tf

{571018: defaultdict(int,
             {4314: 9.181940897454485,
              2840: 8.671115273688494,
              1012: 9.246479418592056,
              1996: 10.750556815368329,
              1037: 3.8712010109078907,
              1997: 4.276666119016055,
              2008: 1.3862943611198906,
              2017: 2.772588722239781,
              1010: 10.499242387087424,
              1005: 1.3862943611198906,
              2031: 1.3862943611198906,
              2000: 0.6931471805599453,
              1998: 1.3862943611198906,
              4163: 0.6931471805599453,
              2411: 1.3862943611198906,
              2004: 0.6931471805599453,
              2005: 0.6931471805599453,
              2030: 0.6931471805599453,
              8882: 0.6931471805599453,
              2236: 0.6931471805599453}),
 832106: defaultdict(int,
             {2138: 0.6931471805599453,
              1997: 10.514990744055563,
              2122: 1.3862943611198906,
              1010: 8.995164990

In [5]:
import torch

In [5]:
# with open('../output/corpus-tf-log-tensor-dict.pkl', 'rb') as f:
#     corpus_tf=pickle.load( f)

In [22]:

with open('../output/corpus-tf-log-tensor-dict.pkl', 'rb') as f:
    cortf=pickle.load( f)

In [12]:
qids=list(s.keys())
batch={}
batch["q_id"]=torch.tensor(qids[:64])

In [44]:
emb=[doc_tf[s[qid.item()]].to_dense()[None,:]for qid in batch['q_id']]

In [71]:
class A:
    def print(self,a):
        return a
class B(A):
    def print(self,a):
        out=super().print([1,2,3])
        
        return *out,a
        

In [72]:
aa=B()

In [73]:
aa.print("faf")

(1, 2, 3, 'faf')

In [46]:
emb1=torch.concat(emb)

In [ ]:
cortf

In [65]:
doc_tf={torch.tensor(key).type(torch.int64):doc_tf[key] for key in doc_tf}

In [82]:
indices=[[],[]]
val=[]
for enumerId,qid in enumerate(batch["q_id"]):
    qid=int(qid.cpu().numpy())
    dim=list(doc_tf[qid].keys())
    indices[0]+=[enumerId]*len(dim)
    indices[1]+=dim
    val+=list(doc_tf[qid].values())

In [84]:
batchSize=len(batch["q_id"])

In [4]:
import torch
a = torch.tensor([[0, 2.], [3, 0]])
b=a.to_sparse()

In [7]:
a-b

tensor([[0., 0.],
        [0., 0.]])